name: release

on:
  release: # Docs: <https://help.github.com/en/articles/events-that-trigger-workflows#release-event-release>
    types: [published]

jobs:
  update-git-tag: # Reason: <https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#recommendations>
    name: Update latest major git tag
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Generate values
        id: values
        run: echo "::set-output name=major::`echo ${GITHUB_REF##*/} | sed 's#^[vV]\([0-9]*\)\..*$#\1#'`"

      - name: Setup git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create tag
        run: git tag -fa "v${{ steps.values.outputs.major }}" -m "Update v${{ steps.values.outputs.major }} tag (using GitHub actions)"

      - name: Push tag
        run: git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" "v${{ steps.values.outputs.major }}" --force
